// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dhcgzqdzytepfutpqtwg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRoY2d6cWR6eXRlcGZ1dHBxdHdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEwNDc4MTYsImV4cCI6MjA3NjYyMzgxNn0.Lkn-a5U_sKw6hMxF1XYSatxB7sur2P_8FFBSilNEr48";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    
  }
});
